### ISSUE TITLE
Looking

### ISSUE THREAD

**Issue by VesnickyTrombonista** [vestr-at-work/simple-birthday-app#1]
Asi bychom mohli normálně zobrazit náš kalendář, do kterého user tlačítkem plus přidá datum narození.
Čekal bych, že při té akci si zadá {jméno, příjmení, datum narození, kontakt} a my mu ty narozeniny hodíme do kalendáře s ročním opakováním, přidáme podle jména i svátek s ročním opakováním.

**Comment by vestr-at-work** [comment]
Yes, to by byla hlavní stránka tý aplikace. Vlastně zbytek by mohl být v tom dialogu přidávání (nastavení kdy (jak moc dopředu) se ti to má připomenout, jestli chceš i svátek atd.). Ještě jsem si tam ale představoval, nějakej způsob jak prostě importovat všechny kontakty a pak si doplnit kdy maj narozeniny nebo vyškrtat ty co nechceš připomínat a tak.

**Comment by VesnickyTrombonista** [comment]
Přemýšlel jsem, že na import kontaktů bychom mohli udělat něco takového, že tam na začátku appky (po instalaci jakoby?) vyskočí okno, jestli chcete ten import a případně editovat ten import.
Takže pak v tom bočním okně by si člověk editoval nastavení notifikací a věcí okolo a vlastně by tam řešil vše ostatní.?
