### ISSUE TITLE
Chronological Event List Fragment

### ISSUE THREAD

**Issue by vestr-at-work** [vestr-at-work/simple-birthday-app#3]
Dodělat Event list fragment aka. nějak pod sebou zobrazit narozeninový události na rok dopředu. Představuju si záznamy s daty sdružený podle měsíců, záznam by měl den v měsíci, avatar, za jak dlouho to je, věk (pokud bude) a edit button na edit záznamu.

**Comment by VesnickyTrombonista** [comment]
Tak jsem dořešil import z databáze. Jenom jestli to z tabulky přesuneš do těch oválných oken a dát do skupinek podle měsíců. 
PS. Zatím ty záznamy nejsou setříděné
