### ISSUE TITLE
Notifications (but BETTER!) 

### ISSUE THREAD

**Issue by vestr-at-work** [vestr-at-work/simple-birthday-app#33]
Máme notifikace, ALE
- nefunguje uplně 100% obnovování každej rok (zatím je to repeating alarm s konstantou cca rok, ale to není přesný. měli bychom mít nějakej způsob, jak po vyslání notifikace naplánujeme další (viz https://stackoverflow.com/questions/48327950/set-repeat-alarm-for-every-year-in-android). also prej se alarmy ruší při vypnutí zařízení, takže to musíme taky ošéfovat a znovu je všechny nahodit.
- taky neřešíme zatím moc runtime permissions, který fungují jen u androidů 12 a výš (API 31)
- TBA

**Comment by vestr-at-work** [comment]
bavil jsem se o tom s kámoškou a možná by bylo lepší udělat repeating alarm jen na začátek každýho dne, kterej by vždycky projel databázi a naplánoval notifikace jen na ten jeden den. tím by se to obnovování vyřešilo a bylo by to vždycky v konzistentním stavu. to vypínání a zapínání ale budem muset vyřešit stejně.

**Comment by VesnickyTrombonista** [comment]
To jsem přemýšlel taky podobně.
Říkal mi nevlastní brácha, že by se dal pustit kron, který by ten řekl, kdo má narozeniny

**Comment by vestr-at-work** [comment]
Tak už jsem promyslel, jak to udělám. Budeme mít ten jeden periodickej alarm, kterej se invokne vždycky po půlnoci a naplánuje všechny notifikace pro lidi co mají narozeniny ten den a taky pro lidi co to mají za X dní (X půjde zvolit v nastavení). V případě, že se mobil vypne, tak se nastartuje tenhle opakující se alarm znova a pokud náhodou ještě není ten čas kdy pro den maj přijít notifikace, tak je naplánuje taky. Pokud už je po tom, tak není potřeba. And thats it. Bude to konzistentní snad furt a hlavně to bude fungovat.
