### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by vestr-at-work** [vestr-at-work/simple-birthday-app#35]
Bylo by cool přidat animace jako při swipování při přesunu z list fragmnetu na calendar fragment a naopak. Taky chybí nějaká smyslupná ikonka v nastavení pro notification hour. +cokoliv dalšího vizuálního

**Comment by VesnickyTrombonista** [comment]
Ok, když mě něco napadne, tak to přidám, ale asi to není tak nutné.
