### ISSUE TITLE
Unintuitive navigation

### ISSUE THREAD

**Issue by vestr-at-work** [vestr-at-work/simple-birthday-app#36]
Když člověk je v jednom z hlavních fragmentů a začne přidávat novej záznam nebo klikne na nastavení/about/import a potom překlikne na druhej z hlavních fragmentů a pak klikne  v bottom navigaci na ten původní fragment, tak to člověka vrátí do přidávání záznamu/nastavení atd. a ne na ten hlavní fragment jako takovej.

**Comment by VesnickyTrombonista** [comment]
Jo, o tom vím, jen jsem nedal issue.
Jako na jednu stránku je fajn, pokud máš rozdělaný záznam a swipneš tam, něco checkneš a pak se vrátíš, tak můžeš pokračovat v editu.
Ale jinak se v tom člověk zamotá a je to asi dost neintuitivní, to je fakt.

**Comment by VesnickyTrombonista** [comment]
Vyřešil jsem, když se přesuneš na druhý fragment, tak se to zahodí, ale jinak si na jednom fragmentu musíš zavřít, co si otevřeš
