### ISSUE TITLE
Input sanitizing

### ISSUE THREAD

**Issue by vestr-at-work** [vestr-at-work/simple-birthday-app#37]
Měli bychom u vstupů nějak kontrolovat jestli jsou ty hodnoty valid a nění tam nějaká SQL injection nebo tak něco. SQL injection možná řeší Room databáze sama, ale ty dny a měsíce bychom testovat měli (aspoň základně) např. existuje 31.2.? Možná by to chtělo využít nějakej widget na vybírání data, ale to taky asi zas tak moc nehoří. Spíš jen abychom to trochu ošetřili.

**Comment by VesnickyTrombonista** [comment]
Jj, to by chtělo filtrovat, jinak ta appka potřebuje reinstalaci
